Feature/event tagging framework typescripts for event api
lassijjk/TurnUp pull request #31
Opened 2023-09-22 08:57 UTC by horridparlor

2023-09-22 09:46 UTC, anhminh10a2hoa commented
remember to run `npm run format` in the client folder

2023-09-22 09:51 UTC, anhminh10a2hoa commented on client/src/components/Cards/EventCard.tsx
> +const EventCard: React.FC = (params: { event: EventObj} ) => {
it should be `const EventCard: React.FC<EventCardProps> = ({ event }: EventCardProps) => {`

2023-09-22 09:54 UTC, anhminh10a2hoa commented on client/src/components/Cards/EventCard.tsx
> +    const [dayTemp, setDay] = useState('0');
`const dayTemp = String(new Date(event.startTime).getUTCDate()).padStart(2, '0')`

2023-09-22 09:58 UTC, anhminh10a2hoa requested changes
remember to run `npm run format` in the client folder

2023-09-25 16:00 UTC, horridparlor commented
Is everything good now?

2023-09-25 18:06 UTC, anhminh10a2hoa approved these changes
Looks good! I will approve it

2023-09-25 19:07 UTC, merged